backend:
  name: github
  repo: Awinocisse/Noor-and-Hikma
  branch: main
  auth_type: implicit
  client_id: "Ov23liw4F2y7StoMxtzk"
  app_id: "Ov23liw4F2y7StoMxtzk"

media_folder: "images"
public_folder: "/images"

collections:
  - name: "articles"
    label: "Articles"
    folder: "articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Contenu", name: "body", widget: "markdown" }
